[tool.poetry]
name = "desafio-cientista-dados-senior-cidadaos-vulneraveis"
version = "0.1.0"
description = "Desafio técnico para Cientista de Dados Sênior no Programa Pequenos Cariocas, Prefeitura do Rio de Janeiro"
authors = ["Marielen Ferreira <marins.marielen@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
pandas = "*"
ipykernel = "^7.2.0"
basedosdados = "^2.0.3"
matplotlib = "*"
seaborn = "*"
scipy = "*"
scikit-learn = "*"
folium = "*"
shapely = "^2.1.2"
jupyter = "^1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
